# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 
# 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. 
# Replace the diagonal elements with 0.
import numpy as np
import random
a1 = np.zeros((5,5),dtype=int)

for i in range(5):
    for j in range(5):
        a1[i][j] = random.randint(1,20)

a1[:][2] = 1
a2 = np.zeros((4,4),dtype=int)
num=1
for i in range(4):
    for j in range(4):
        a2[i][j] = num
        num+=1
for i in range(4):
    a2[i][i]=0
print(a1)
print(a2)




[[ 6 16  4 19 15]
 [15  8 16 15  7]
 [ 1  1  1  1  1]
 [ 2  8  8 12  1]
 [19 13  2 20  4]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [7]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
# Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the 
# elements on the border.
num=1
a1 = np.zeros((6,6), dtype=int)
for i in range(6):
    for j in range(6):
        a1[i][j] = num
        num+=1
print(a1[2:5,1:4])

a2 = np.zeros((5,5),dtype=int)
for i in range(5):
    for j in range(5):
        a2[i][j] = random.randint(1,25)
print(a2)
for j in range(5):
    print(a2[0][j], end=" ")

for j in range(5):
    print(a2[4][j], end=" ")

for i in range(1,4):
    print(a2[i][0], end=" ")
for i in range(1,4):
    print(a2[i][4], end=" ")




[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[10 25 20 17 24]
 [14 11 17 20 20]
 [16  7  6 13  2]
 [17 20  1 21 23]
 [24 17 11  8  5]]
10 25 20 17 24 24 17 11 8 5 14 16 17 20 2 23 

In [16]:
# 1. Create two NumPy arrays of shape (3, 4) filled with random integers.
#  Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute 
# the row-wise and column-wise sum.
import numpy as np
import random
a1 = np.random.randint(1, 20, size=(4,4))
a2 = np.random.randint(1, 20, size=(4,4))
print(a1)
print(a2)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

a3 = np.arange(1,17).reshape(4,4)
row_sum = a3.sum(axis=1)
col_sum = a3.sum(axis=0)
print(a3)
print(row_sum)
print(col_sum)

[[13 14 11 18]
 [16  4  2 18]
 [16 15 13  6]
 [ 9  7 17  1]]
[[ 7  3  9 18]
 [ 4 11 13  2]
 [18 15 11 12]
 [11  6 14 10]]
[[20 17 20 36]
 [20 15 15 20]
 [34 30 24 18]
 [20 13 31 11]]
[[  6  11   2   0]
 [ 12  -7 -11  16]
 [ -2   0   2  -6]
 [ -2   1   3  -9]]
[[ 91  42  99 324]
 [ 64  44  26  36]
 [288 225 143  72]
 [ 99  42 238  10]]
[[1.85714286 4.66666667 1.22222222 1.        ]
 [4.         0.36363636 0.15384615 9.        ]
 [0.88888889 1.         1.18181818 0.5       ]
 [0.81818182 1.16666667 1.21428571 0.1       ]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [19]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers.
#  Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a 
# standard deviation of 1).
a1 = np.random.randint(1,25 ,size=(5,5))
a2 = np.arange(1,10).reshape(3,3)

print(f"mean is {np.mean(a1)}")
print(f"median is {np.median(a1)}")
print(f"std is {np.std(a1)}")
print(f"var is {np.var(a1)}")

mean = np.mean(a2)
std_dev = np.std(a2)

# Normalize the data
normalized_data = (a2 - mean) / std_dev
print("Normalized data:", normalized_data)


mean is 10.72
median is 11.0
std is 7.03431588713501
var is 49.4816
Normalized data: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [20]:
# 1. Create a NumPy array of shape (3, 3) filled with random integers.
#  Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract
#  a 1D array of shape (4,) from each column of the 2D array using broadcasting.
import numpy as np
a = np.random.randint(1, 10, size=(3, 3))
b = np.array([1, 2, 3])
result = a + b
print("2D Array:")
print(a)
print("1D Array:")
print(b)
print("After Broadcasting row-wise addition:")
print(result)


c = np.random.randint(10, 50, size=(4, 4))
d = np.array([1, 2, 3, 4])
res = c - d.reshape(4, 1)
print("2D Array:")
print(c)
print("1D Array:")
print(d)
print("After Broadcasting (column-wise subtraction):")
print(res)



2D Array:
[[8 9 2]
 [3 9 5]
 [5 1 1]]
1D Array:
[1 2 3]
After Broadcasting row-wise addition:
[[ 9 11  5]
 [ 4 11  8]
 [ 6  3  4]]
2D Array:
[[43 28 24 44]
 [27 22 42 47]
 [12 41 13 17]
 [19 10 38 25]]
1D Array:
[1 2 3 4]
After Broadcasting (column-wise subtraction):
[[42 27 23 43]
 [25 20 40 45]
 [ 9 38 10 14]
 [15  6 34 21]]


In [21]:
# 1. Create a NumPy array of shape (3, 3) representing a matrix. 
# Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform 
# matrix multiplication on these arrays.
A = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 8]
])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigenvalues = np.linalg.eigvals(A)
print("Matrix A:")
print(A)
print("\nDeterminant:", det)
print("\nInverse:")
print(inv)
print("\nEigenvalues:")
print(eigenvalues)



a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])   

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])   

result = np.dot(A, B)

print("Result of matrix multiplication:")
print(result)


Matrix A:
[[2 1 3]
 [1 0 2]
 [4 1 8]]

Determinant: -1.0

Inverse:
[[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]

Eigenvalues:
[ 9.88864745  0.37851665 -0.26716411]
Result of matrix multiplication:
[[20 26]
 [11 14]
 [47 60]]


In [25]:
# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. 
# Flatten the array and then reshape it back to (5, 5).
a1 = np.arange(1,10).reshape(3,3)
print(a1)
ax = a1.reshape((1,9))
print(ax)
ay = a1.reshape((9,1))
print(ay)

a2 = np.random.randint(1,25 , size=(5,5))
print(a2)
aq = a2.flatten()
print(aq)
az = a2.reshape((5,5))
print(az)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[17  7  2 13 15]
 [11 11  7  2 10]
 [23 17 24  9 12]
 [19  5 12 19  5]
 [ 2 14  4  3 11]]
[17  7  2 13 15 11 11  7  2 10 23 17 24  9 12 19  5 12 19  5  2 14  4  3
 11]
[[17  7  2 13 15]
 [11 11  7  2 10]
 [23 17 24  9 12]
 [19  5 12 19  5]
 [ 2 14  4  3 11]]


In [27]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. 
# Use fancy indexing to extract the elements at the corners of the array.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. 
# Use boolean indexing to set all elements greater than 10 to 10.

a = np.random.randint(1, 25, size=(5,5))
print("Array:")
print(a)
corners = a[[0, 0, 4, 4], [0, 4, 0, 4]]
print("Corner elements:", corners)

b = np.random.randint(1, 20, size=(4,4))
print("Before:")
print(b)
print(b[b>10])
b[b > 10] = 10
print("After setting values > 10 to 10:")
print(b)


Array:
[[ 2 11  7 10 19]
 [13 11 24  6  8]
 [23 12 21 21  3]
 [21  5 18  6  9]
 [11  7 14  1  7]]
Corner elements: [ 2 19 11  7]
Before:
[[17 17  3  1]
 [ 5 17 17 13]
 [19  8  1  6]
 [13 10 18 11]]
[17 17 17 17 13 19 13 18 11]
After setting values > 10 to 10:
[[10 10  3  1]
 [ 5 10 10 10]
 [10  8  1  6]
 [10 10 10 10]]


In [28]:
# 1. Create a structured array with fields 'name' (string), 'age' (integer), and
#  'weight' (float). Add some data and sort the array by age.
# 2. Create a structured array with fields 'x' and 'y' (both integers). 
# Add some data and compute the Euclidean distance between each pair of points.
import numpy as np
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
people = np.array([
    ('Aroosh', 22, 60.5),
    ('Ravi', 25, 70.2),
    ('Anil', 20, 55.0),
    ('John', 23, 68.4)
], dtype=dtype)
print("Before sorting:")
print(people)
sorted_people = np.sort(people, order='age')

print("\nAfter sorting by age:")
print(sorted_people)


dtype = [('x', 'i4'), ('y', 'i4')]

points = np.array([
    (1, 2),
    (4, 6),
    (8, 10),
    (3, 7)
], dtype=dtype)

print("Points:")
print(points)
distances = np.sqrt(points['x']**2 + points['y']**2)

print("\nEuclidean distances from origin:")
print(distances)


Before sorting:
[('Aroosh', 22, 60.5) ('Ravi', 25, 70.2) ('Anil', 20, 55. )
 ('John', 23, 68.4)]

After sorting by age:
[('Anil', 20, 55. ) ('Aroosh', 22, 60.5) ('John', 23, 68.4)
 ('Ravi', 25, 70.2)]
Points:
[(1,  2) (4,  6) (8, 10) (3,  7)]

Euclidean distances from origin:
[ 2.23606798  7.21110255 12.80624847  7.61577311]


In [30]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the 
# elements greater than 10. Compute the sum of the unmasked elements.
# 2. Create a masked array of shape (3, 3) with random integers and mask the
# diagonal elements. Replace the masked elements with the mean of the unmasked 
# elements.
import numpy as np
a = np.random.randint(1, 20, size=(4,4))
print("Original array:")
print(a)
masked_arr = np.ma.masked_where(a > 10, a)

print("\nMasked array:")
print(masked_arr)
print("\nSum of unmasked elements:", masked_arr.sum())



b = np.random.randint(1, 20, size=(3,3))
print("Original array:")
print(b)
mask = np.eye(3, dtype=bool)
masked_b = np.ma.array(b, mask=mask)

print("\nMasked array (diagonal masked):")
print(masked_b)

# Compute mean of unmasked values
mean_val = masked_b.mean()

# Replace masked elements with mean
filled_array = masked_b.filled(mean_val)

print("\nFinal array after replacing masked with mean:")
print(filled_array)



Original array:
[[12  8 12 15]
 [17 10 13 12]
 [ 9  1  8  4]
 [16 13 15  3]]

Masked array:
[[-- 8 -- --]
 [-- 10 -- --]
 [9 1 8 4]
 [-- -- -- 3]]

Sum of unmasked elements: 43
Original array:
[[13  3  5]
 [10  5 13]
 [ 6  7 14]]

Masked array (diagonal masked):
[[-- 3 5]
 [10 -- 13]
 [6 7 --]]

Final array after replacing masked with mean:
[[ 7  3  5]
 [10  7 13]
 [ 6  7  7]]
